# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DaXiaDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DaXiaDemo
  pod 'Da'
  pod 'Xia'

  target 'DaXiaDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DaXiaDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
